name: ${project.name}
main: com.elitelogs.EliteLogsPlugin
version: ${project.version}
author: Elite
softdepend:
  - ProtocolLib
commands:
  elitelogs:
    aliases: [elogs]
    description: EliteLogs administrative command
    usage: |
      /elitelogs help
      /elitelogs reload
      /elitelogs version
      /elitelogs export [today|full|last-crash]
      /elitelogs inspector [all|plugins|mods|configs|garbage|server]
      /elitelogs logs [toggle <type>]
      /elitelogs metrics [now]
      /elitelogs rotate
      /elitelogs session [last]
    permission: elogs.admin
permissions:
  elogs.admin:
    default: op
