# ============================
#  EliteLogs Configuration
#  (All comments are English only)
# ============================
# Encoding: UTF-8 (no BOM)
# Indentation: 2 spaces (tabs are NOT allowed)

enabled: true
debug: false
language: en

ansi:
  enabled: true
  color-ok: "§a"
  color-warn: "§e"
  color-fail: "§c"
  reset: "§f"

banner:
  enabled: true
  show-version: true
  style: block
  color: default

discord:
  enabled: false
  webhook-url: ""
  rate-limit-seconds: 10
  send:
    errors: true
    warns: true
    sessions: true
    watchdog: true
    inspector: true

logs:
  rotate: true
  keep-days: 30
  archive: true
  split-by-player: true
  legacy:
    flat-player-files: false
  types:
    info: true
    warns: true
    errors: true
    chat: true
    commands: true
    players: true
    combat: true
    inventory: true
    economy: true
    stats: true
    console: true
    suppressed: true

sessions:
  enabled: true
  autosave-minutes: 10
  save-global: true
  save-players: true

inspector:
  enabled: true
  include-mods: true
  include-configs: true
  include-garbage: true
  include-server-info: true

metrics:
  enabled: true
  interval-seconds: 60

suppressor:
  enabled: true
  mode: blacklist
  spam-limit: 1000
  filters: []

watchdog:
  enabled: true
  tps-threshold: 5.0
  error-threshold: 50
  actions:
    run-inspector: true
    create-crash-report: true
    discord-alert: true
